name: FastAPI CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check Docker Compose Version
        run: docker-compose --version

      - name: Build and Push Docker Image
        run: |
          
          IMAGE_TAG=$(git rev-parse --short HEAD) 
          
          DOCKER_REPO=${{ secrets.DOCKER_USERNAME }}/fastapi
          
          DOCKER_REPO=$DOCKER_REPO TAG=$IMAGE_TAG docker compose build
          
          docker tag $DOCKER_REPO:$IMAGE_TAG $DOCKER_REPO:latest
          
          docker push $DOCKER_REPO:$IMAGE_TAG
          docker push $DOCKER_REPO:latest

        # Set the image tag to the short Git SHA
        # Define the Docker repository name
        # Build the image with docker-compose, setting TAG as an environment variable
        # Tag the image with 'latest'
        # Push both tagged images to Docker Hub